# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Sets user-defined palette
# Palettes must be defined _after_ this line
palette = "catppuccin_mocha"

format = "$os$username$hostname$directory$git_branch$git_commit\n$character"

# Starship modules
[character]
# Note the use of Catppuccin color 'peach'
success_symbol = "[❯](peach)"
error_symbol = "[❯](peach)"
vimcmd_symbol = "[❮](subtext1)" # For use with zsh-vi-mode

[palettes.catppuccin_mocha]
rosewater = "#f5e0dc"
flamingo = "#f2cdcd"
pink = "#f5c2e7"
mauve = "#cba6f7"
red = "#f38ba8"
maroon = "#eba0ac"
peach = "#fab387"
yellow = "#f9e2af"
green = "#a6e3a1"
teal = "#94e2d5"
sky = "#89dceb"
sapphire = "#74c7ec"
blue = "#89b4fa"
lavender = "#b4befe"
text = "#cdd6f4"
subtext1 = "#bac2de"
subtext0 = "#a6adc8"
overlay2 = "#9399b2"
overlay1 = "#7f849c"
overlay0 = "#6c7086"
surface2 = "#585b70"
surface1 = "#45475a"
surface0 = "#313244"
base = "#1e1e2e"
mantle = "#181825"
crust = "#11111b"

[git_branch]
symbol = ""
format = "[$symbol$branch(:$remote_branch)]($style) "
style = "bold mauve"

[directory]
truncation_length = 4
style = "bold lavender"

[os.symbols]
Ubuntu = "\ue73a "
Unknown = "❓ "
Windows = "\ue70f "
Arch = "\uf303 "

[os]
disabled = false
# format = "[$symbol$type ]($style)"
style = "bold blue"

[username]
show_always = true
disabled = false
format = "[$user]($style) "
style_user = "yellow bold"

[hostname]
# ssh_only = false
format = "[$ssh_symbol$hostname]($style) "
style = "sapphire bold"
